### ISSUE TITLE
gconnect() Error

### ISSUE THREAD

**Issue by Patrikios** [ecsalina/gtrends#2]
Hi, 
it would be great if you could point out to me what the error below means, it occurs while I try to connect with my gmail login credentials:
    Error in function (type, msg, asError = TRUE)  : 
       Could not resolve host: accounts.google.com
Thnx in advance!

**Comment by ecsalina** [comment]
Hi Patrikios,
While I too was unable to login, I was unable to reproduce your specific error as of yet. It does look like Google recently changed one of its hidden fields (called "GALX"), which did prevent me from logging in, but after I fixed that everything is working just fine. That could've been your issue. I'll be pushing out the patch in a new version of gtrends today. Do you have any more info on the issue? Otherwise, try the updated version and see if there are still errors.
